// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt5DpTzq_7rkVDMXTNWX5N0cXe31wIh7w',
    appId: '1:936027519451:web:8668578da3e58168340ffe',
    messagingSenderId: '936027519451',
    projectId: 'todo-app-1e926',
    authDomain: 'todo-app-1e926.firebaseapp.com',
    storageBucket: 'todo-app-1e926.firebasestorage.app',
    measurementId: 'G-T4RN8VDHHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhftWsZoPD9Rf8EOYaQTyceoNssafQiKk',
    appId: '1:936027519451:android:9bdf81905c0d3679340ffe',
    messagingSenderId: '936027519451',
    projectId: 'todo-app-1e926',
    storageBucket: 'todo-app-1e926.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPrAHaL2SkKgYxzuaNyE9OF1YkCQO5KMw',
    appId: '1:936027519451:ios:d64cc01805e59d56340ffe',
    messagingSenderId: '936027519451',
    projectId: 'todo-app-1e926',
    storageBucket: 'todo-app-1e926.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPrAHaL2SkKgYxzuaNyE9OF1YkCQO5KMw',
    appId: '1:936027519451:ios:d64cc01805e59d56340ffe',
    messagingSenderId: '936027519451',
    projectId: 'todo-app-1e926',
    storageBucket: 'todo-app-1e926.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt5DpTzq_7rkVDMXTNWX5N0cXe31wIh7w',
    appId: '1:936027519451:web:e99887f4bdc2280d340ffe',
    messagingSenderId: '936027519451',
    projectId: 'todo-app-1e926',
    authDomain: 'todo-app-1e926.firebaseapp.com',
    storageBucket: 'todo-app-1e926.firebasestorage.app',
    measurementId: 'G-VYM056ZY1T',
  );
}
