// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdBbbPjmlHx7CtZ_UY1AOJN-Frg6ewMT0',
    appId: '1:7825873897:web:0c6575a7d971baa6b50978',
    messagingSenderId: '7825873897',
    projectId: 'tourism-app-d113c',
    authDomain: 'tourism-app-d113c.firebaseapp.com',
    storageBucket: 'tourism-app-d113c.firebasestorage.app',
    measurementId: 'G-YBTFZPN9QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSqGWvycerpiNtYp_ajE5xtUZC8ykzZRo',
    appId: '1:7825873897:android:9f0d831cb3f52229b50978',
    messagingSenderId: '7825873897',
    projectId: 'tourism-app-d113c',
    storageBucket: 'tourism-app-d113c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAofW5rz4ryZOW3AJH5b9EcCjqx_DOYiIw',
    appId: '1:7825873897:ios:9f41c85de18f1d18b50978',
    messagingSenderId: '7825873897',
    projectId: 'tourism-app-d113c',
    storageBucket: 'tourism-app-d113c.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAofW5rz4ryZOW3AJH5b9EcCjqx_DOYiIw',
    appId: '1:7825873897:ios:9f41c85de18f1d18b50978',
    messagingSenderId: '7825873897',
    projectId: 'tourism-app-d113c',
    storageBucket: 'tourism-app-d113c.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdBbbPjmlHx7CtZ_UY1AOJN-Frg6ewMT0',
    appId: '1:7825873897:web:dda03f17498f560fb50978',
    messagingSenderId: '7825873897',
    projectId: 'tourism-app-d113c',
    authDomain: 'tourism-app-d113c.firebaseapp.com',
    storageBucket: 'tourism-app-d113c.firebasestorage.app',
    measurementId: 'G-R5F62MZPP2',
  );
}
